### ISSUE TITLE
Can't create/load/import world

### ISSUE THREAD

**Issue by DearFox** [Dev7ex/MultiWorld#21]
I updated the server from 1.19.4 to 1.20.1
I am using purpur-1.20.1-2050
I have installed MultiWorld-Bukkit-1.4.5-SNAPSHOT and also FacilisCommon-Bukkit-1.0.2-SNAPSHOT

But I get an error when I try to do one of the create/load/import world commands

```
[16:17:45 INFO]: DearFox issued server command: /multiworld create test_world VOID
[16:17:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'multiworld' in plugin MultiWorld v1.4.5-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1021) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2447) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java:2407) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2050]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.HashMap.get(Object)" is null
        at com.dev7ex.common.map.ParsedMap.getString(ParsedMap.java:26) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at com.dev7ex.common.map.ParsedMap.getBoolean(ParsedMap.java:82) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at com.dev7ex.multiworld.world.DefaultWorldManager.createWorld(DefaultWorldManager.java:174) ~[MultiWorld-Bukkit-1.4.5-SNAPSHOT.jar:?]
        at com.dev7ex.multiworld.command.world.CreateCommand.execute(CreateCommand.java:61) ~[MultiWorld-Bukkit-1.4.5-SNAPSHOT.jar:?]
        at com.dev7ex.common.bukkit.command.BukkitCommand.execute(BukkitCommand.java:38) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:59) ~[MultiWorld-Bukkit-1.4.5-SNAPSHOT.jar:?]
        at com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:26) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by Dev7ex** [comment]
What happens if you delete the config.yml once?

**Comment by DearFox** [comment]
> What happens if you delete the config.yml once?

It seems that this actually caused an error, since now I imported worlds without any problems and the command no longer caused an error.
 I don't remember changing something in config.yml so that it was my default config from the old version.

**Comment by Dev7ex** [comment]
I'll leave the issue for a while in case there is an error again just report it

**Comment by jokbon** [comment]
[05:00:34 ERROR]: [Minecraft] null
org.bukkit.command.CommandException: Unhandled exception executing command 'world' in plugin MultiWorld v1.4.6-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-131]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2342) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2302) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-131]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.HashMap.get(Object)" is null
        at com.dev7ex.common.map.ParsedMap.getString(ParsedMap.java:26) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at com.dev7ex.common.map.ParsedMap.getBoolean(ParsedMap.java:82) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at com.dev7ex.multiworld.world.DefaultWorldManager.importWorld(DefaultWorldManager.java:364) ~[MultiWorld-Bukkit-1.4.6-SNAPSHOT.jar:?]
        at com.dev7ex.multiworld.command.world.ImportCommand.execute(ImportCommand.java:62) ~[MultiWorld-Bukkit-1.4.6-SNAPSHOT.jar:?]
        at com.dev7ex.common.bukkit.command.BukkitCommand.execute(BukkitCommand.java:38) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:59) ~[MultiWorld-Bukkit-1.4.6-SNAPSHOT.jar:?]
        at com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:26) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by jokbon** [comment]
more information coming in future.
