### ISSUE TITLE
Errors at /world clone and /world backup

### ISSUE THREAD

**Issue by pref6** [Dev7ex/MultiWorld#39]
When I use the commands /world clone and /world backup, I get a lot of errors in the console and in the game chat "An internal error occurred while attempting to perform this command". The worlds themselves are not cloned and backups are not created. Installed FacilisCommon version 1.0.5-SNAPHOST. I am using Purpur kernel 1.16.5 and Java version 17. Here is the error /world clone:

[22:28:08] [Server thread/INFO]: ToxCraft issued server command: /world clone Conquistador Newmap
[22:28:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'world' in plugin MultiWorld v1.6.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2315) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at com.dev7ex.multiworld.world.DefaultWorldManager.cloneWorld(DefaultWorldManager.java:87) ~[?:?]
	at com.dev7ex.multiworld.command.world.CloneCommand.execute(CloneCommand.java:43) ~[?:?]
	at com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:65) ~[?:?]
	at com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:26) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.dev7ex.multiworld.world.DefaultWorldManager.cloneWorld(DefaultWorldManager.java:87) ~[?:?]
	at com.dev7ex.multiworld.command.world.CloneCommand.execute(CloneCommand.java:43) ~[?:?]
	at com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:65) ~[?:?]
	at com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:26) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 19 more

And /world backup error:

[22:42:56] [Server thread/INFO]: ToxCraft issued server command: /world backup Conquistador
[22:42:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'world' in plugin MultiWorld v1.6.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2315) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at com.dev7ex.multiworld.world.DefaultWorldManager.createBackup(DefaultWorldManager.java:131) ~[?:?]
	at com.dev7ex.multiworld.command.world.BackupCommand.execute(BackupCommand.java:43) ~[?:?]
	at com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:65) ~[?:?]
	at com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:26) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at com.dev7ex.multiworld.world.DefaultWorldManager.createBackup(DefaultWorldManager.java:131) ~[?:?]
	at com.dev7ex.multiworld.command.world.BackupCommand.execute(BackupCommand.java:43) ~[?:?]
	at com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:65) ~[?:?]
	at com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:26) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 19 more

**Comment by Dev7ex** [comment]
Are you using the latest MultiWorld version?

**Comment by pref6** [comment]
Yes, i use 1.6.0 snapshot multiworld and faciliscommon 1.0.5 snapshot.

**Comment by Dev7ex** [comment]
Found the error will be fixed later
