### ISSUE TITLE
Plugin commands don't work

### ISSUE THREAD

**Issue by Wasdergingame** [Dev7ex/MultiWorld#41]
Message from the console:

```
[MultiWorld] Error initializing plugin 'MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'reader', line 60, column 1:
    <<<<<<< Updated upstream
    ^
could not find expected ':'
 in 'reader', line 62, column 1:
    messages:
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:502) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:307) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:237) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:637) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:486) ~[snakeyaml-2.2.jar:?]
        at FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar/com.dev7ex.common.io.file.configuration.YamlConfiguration.load(YamlConfiguration.java:106) ~[FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar:?]
        at FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar/com.dev7ex.common.io.file.configuration.YamlConfiguration.load(YamlConfiguration.java:74) ~[FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar:?]
        at FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar/com.dev7ex.common.io.file.configuration.YamlConfiguration.load(YamlConfiguration.java:66) ~[FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar:?]
        at FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar/com.dev7ex.common.io.file.configuration.Configuration.loadFile(Configuration.java:51) ~[FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar:?]
        at FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar/com.dev7ex.common.bukkit.plugin.configuration.DefaultPluginConfiguration.load(DefaultPluginConfiguration.java:23) ~[FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldConfiguration.load(MultiWorldConfiguration.java:44) ~[MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldPlugin.onLoad(MultiWorldPlugin.java:61) ~[MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-119-100d75a]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-119-100d75a]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-119-100d75a]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-119-100d75a]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-119-100d75a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
Message from the console when using the command:

```
Command exception: /multiworld
org.bukkit.command.CommandException: Unhandled exception executing command 'multiworld' in plugin MultiWorld v1.6.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-119-100d75a]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.jar:1.21-119-100d75a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-119-100d75a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.dev7ex.common.io.file.configuration.FileConfiguration.getStringList(String)" because the return value of "com.dev7ex.common.bukkit.plugin.configuration.DefaultPluginConfiguration.getFileConfiguration()" is null
        at FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar/com.dev7ex.common.bukkit.plugin.configuration.DefaultPluginConfiguration.getStringList(DefaultPluginConfiguration.java:83) ~[FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar/com.dev7ex.multiworld.command.world.HelpCommand.execute(HelpCommand.java:22) ~[MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar/com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:58) ~[MultiWorld-Bukkit-1.6.0-SNAPSHOT.jar:?]
        at FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar/com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:26) ~[FacilisCommon-Bukkit-1.0.5-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        ... 27 more
```

**Comment by Dev7ex** [comment]
Fixed in version 1.6.4-SNAPSHOT
