### ISSUE TITLE
17.08 17:45:44 [Server] ERROR Could not pass event EntityPortalEvent to MultiWorld v1.6.4-SNAPSHOT

### ISSUE THREAD

**Issue by Illustive** [Dev7ex/MultiWorld#43]
17.08 17:45:44 [Server] ERROR Could not pass event EntityPortalEvent to MultiWorld v1.6.4-SNAPSHOT
17.08 17:45:44 [Server] INFO java.util.NoSuchElementException: No value present
17.08 17:45:44 [Server] INFO at java.base/java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
17.08 17:45:44 [Server] INFO at MultiWorld-Bukkit-1.6.4-SNAPSHOT.jar/com.dev7ex.multiworld.listener.entity.EntityPortalListener.handleEntityEnterPortal(EntityPortalListener.java:43) ~[MultiWorld-Bukkit-1.6.4-SNAPSHOT.jar:?]
17.08 17:45:44 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor708.execute(Unknown Source) ~[?:?]
17.08 17:45:44 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
17.08 17:45:44 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
17.08 17:45:44 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
17.08 17:45:44 [Server] INFO at net.minecraft.world.entity.Entity.callPortalEvent(Entity.java:3923) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.world.level.block.NetherPortalBlock.getPortalDestination(NetherPortalBlock.java:168) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.world.entity.PortalProcessor.getPortalDestination(PortalProcessor.java:33) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.world.entity.Entity.handlePortal(Entity.java:3329) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.world.entity.Entity.postTick(Entity.java:887) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1331) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:761) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1844) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:44 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

17.08 17:45:45 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:45 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:45 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2289-201e928]
17.08 17:45:45 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by mpcabral** [comment]
Same here :(

**Comment by Dev7ex** [comment]
I'll have a look at this

**Comment by Dev7ex** [comment]
How exactly did this error occur?

**Comment by Dev7ex** [comment]
My only explanation is that you have another world system which has loaded a world that MultiWorld doesn't know about. 

I will leave the issue open for 7 days if there is no response by then it will be deleted
