### ISSUE TITLE
PaperMC 1.20.6 error by MultiWorld-1.6.6-SNAPSHOT

### ISSUE THREAD

**Issue by TheReizi** [Dev7ex/MultiWorld#49]
[MultiWorld] Error initializing plugin 'MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar' in folder 'plugins\.paper-remapped' (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.dev7ex.multiworld.api.world.WorldDefaultProperty.LOAD_AUTO
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.craftbukkit.legacy.FieldRename.valueOf(FieldRename.java:57) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar/com.dev7ex.multiworld.api.world.WorldDefaultProperty.BUKKIT_CUSTOM_METHOD_org_bukkit_craftbukkit_legacy_FieldRename_valueOf(WorldDefaultProperty.java) ~[MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar/com.dev7ex.multiworld.api.world.WorldDefaultProperty.valueOf(WorldDefaultProperty.java:17) ~[MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldConfiguration.lambda$load$0(MultiWorldConfiguration.java:65) ~[MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldConfiguration.load(MultiWorldConfiguration.java:65) ~[MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldPlugin.onLoad(MultiWorldPlugin.java:63) ~[MultiWorld-Bukkit-1.6.6-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:532) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by GodzHardYT** [comment]
same problem

**Comment by Dev7ex** [comment]
Please read the changelog. You have to delete the old config.yml

https://www.spigotmc.org/resources/multiworld-bukkit.92559/updates
