### ISSUE TITLE
MultiWorld v1.6.9-SNAPSHOT Error on world loading

### ISSUE THREAD

**Issue by AllRoundJonU** [Dev7ex/MultiWorld#51]
Server Version: Paper 1.21.1
MultiWorld Version: MultiWorld v1.6.9-SNAPSHOT

When I try to load an imported world I get follwing error:

```
[21:05:02 ERROR]: Command exception: /mw load DungeonTwo
org.bukkit.command.CommandException: Unhandled exception executing command 'mw' in plugin MultiWorld v1.6.9-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1627) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Illegal dimension (CUSTOM)
        at org.bukkit.craftbukkit.CraftServer.createWorld(CraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:838) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.9-SNAPSHOT.jar/com.dev7ex.multiworld.world.DefaultWorldManager.loadWorld(DefaultWorldManager.java:555) ~[MultiWorld-Bukkit-1.6.9-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.9-SNAPSHOT.jar/com.dev7ex.multiworld.command.world.LoadCommand.execute(LoadCommand.java:54) ~[MultiWorld-Bukkit-1.6.9-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.9-SNAPSHOT.jar/com.dev7ex.multiworld.command.WorldCommand.execute(WorldCommand.java:76) ~[MultiWorld-Bukkit-1.6.9-SNAPSHOT.jar:?]
        at FacilisCommon-Bukkit-1.0.6-SNAPSHOT.jar/com.dev7ex.common.bukkit.command.BukkitCommandExecutor.onCommand(BukkitCommandExecutor.java:47) ~[FacilisCommon-Bukkit-1.0.6-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 26 more```
        
What did I do?

1. `/mw import WorldName CUSTOM -g VoidWorldGenerator`
2. `/mw load WorldName`

**Comment by Dev7ex** [comment]
The custom doesn't really work in the Minecraft server. Just use normal. This specification is the environment so how the sky looks there it is not particularly relevant whether custom or normal
