### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aleksplay11** [Dev7ex/MultiWorld#52]
[14:24:12 WARN]: java.lang.NullPointerException: Cannot invoke "com.dev7ex.common.io.file.configuration.FileConfiguration.contains(String)" because the return value of "com.dev7ex.common.io.file.configuration.Configuration.getFileConfiguration()" is null
[14:24:12 WARN]:        at com.dev7ex.multiworld.world.DefaultWorldConfiguration.contains(DefaultWorldConfiguration.java:117)
[14:24:12 WARN]:        at com.dev7ex.multiworld.world.DefaultWorldProvider.onEnable(DefaultWorldProvider.java:59)
[14:24:12 WARN]:        at com.dev7ex.common.bukkit.plugin.module.PluginModuleManager.enableAllModules(PluginModuleManager.java:49)
[14:24:12 WARN]:        at com.dev7ex.common.bukkit.BukkitCommonPlugin.handlePluginEnable(BukkitCommonPlugin.java:73)
[14:24:12 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source)
[14:24:12 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[14:24:12 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:24:12 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:24:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[14:24:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:381)
[14:24:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:24:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[14:24:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[14:24:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599)
[14:24:12 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[14:24:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[14:24:12 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[14:24:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831

**Comment by Dev7ex** [comment]
Please send the full log

**Comment by aleksplay11** [comment]
So i need multiworld plugin to play speedbuilders that only can be played on 1.16.5 version, so i use version of plugins that uses jdk 16 and not 17, if ill set jdk to 17 it gives me an error, that only up to jdk 16 is supported, my free hosting uses paper and has startup command, but i cant edit it to place -dpaper.ignorejavaversion thing.

Logs:

[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
Skynode: Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.2+7) Host: Linux 5.15.0-125-generic (amd64)
Loading libraries, please wait...
[12:23:20 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:23:21 INFO]: Reloading ResourceManager: Default, bukkit
[12:23:23 INFO]: Loaded 7 recipes
[12:23:27 INFO]: Starting minecraft server version 1.16.5
[12:23:27 INFO]: Loading properties
[12:23:27 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[12:23:27 INFO]: Debug logging is disabled
[12:23:27 INFO]: Server Ping Player Sample Count: 12
[12:23:27 INFO]: Using 4 threads for Netty based IO
[12:23:28 INFO]: Default game type: SURVIVAL
[12:23:28 INFO]: Generating keypair
[12:23:28 INFO]: Starting Minecraft server on 0.0.0.0:27296
[12:23:29 INFO]: Using epoll channel type
[12:23:30 INFO]: [FacilisCommon] Loading 3 libraries... please wait
[12:23:30 INFO]: [FacilisCommon] Loaded library /home/container/libraries/net/kyori/adventure-api/4.13.0/adventure-api-4.13.0.jar
[12:23:30 INFO]: [FacilisCommon] Loaded library /home/container/libraries/net/kyori/adventure-key/4.13.0/adventure-key-4.13.0.jar
[12:23:30 INFO]: [FacilisCommon] Loaded library /home/container/libraries/net/kyori/examination-api/1.3.0/examination-api-1.3.0.jar
[12:23:30 INFO]: [FacilisCommon] Loaded library /home/container/libraries/net/kyori/examination-string/1.3.0/examination-string-1.3.0.jar
[12:23:30 INFO]: [FacilisCommon] Loaded library /home/container/libraries/org/jetbrains/annotations/24.0.1/annotations-24.0.1.jar
[12:23:30 INFO]: [FacilisCommon] Loaded library /home/container/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[12:23:30 INFO]: [FacilisCommon] Loaded library /home/container/libraries/commons-io/commons-io/2.10.0/commons-io-2.10.0.jar
[12:23:30 INFO]: [MultiWorld] Loading 4 libraries... please wait
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-api/4.17.0/adventure-api-4.17.0.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-key/4.17.0/adventure-key-4.17.0.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/examination-api/1.3.0/examination-api-1.3.0.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/examination-string/1.3.0/examination-string-1.3.0.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/org/jetbrains/annotations/24.1.0/annotations-24.1.0.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-text-minimessage/4.17.0/adventure-text-minimessage-4.17.0.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-platform-bukkit/4.3.3/adventure-platform-bukkit-4.3.3.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-platform-api/4.3.3/adventure-platform-api-4.3.3.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-text-serializer-bungeecord/4.3.3/adventure-text-serializer-bungeecord-4.3.3.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-text-serializer-legacy/4.13.1/adventure-text-serializer-legacy-4.13.1.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-nbt/4.13.1/adventure-nbt-4.13.1.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-text-serializer-gson/4.13.1/adventure-text-serializer-gson-4.13.1.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-text-serializer-gson-legacy-impl/4.13.1/adventure-text-serializer-gson-legacy-impl-4.13.1.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-platform-facet/4.3.3/adventure-platform-facet-4.3.3.jar
[12:23:31 INFO]: [MultiWorld] Loaded library /home/container/libraries/net/kyori/adventure-platform-viaversion/4.3.3/adventure-platform-viaversion-4.3.3.jar
[12:23:31 INFO]: [FacilisCommon] Loading FacilisCommon v1.0.5-SNAPSHOT
[12:23:31 INFO]: [MultiWorld] Loading MultiWorld v1.6.7-SNAPSHOT
[12:23:31 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] java.io.EOFException: End of input at line 1 column 2 path $. initializing MultiWorld v1.6.7-SNAPSHOT (Is it up to date?)
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 2 path $.
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.gson.Gson.fromJson(Gson.java:825) ~[patched_1.16.5.jar:git-Paper-794]
        at com.dev7ex.common.io.file.configuration.JsonConfiguration.load(JsonConfiguration.java:66) ~[?:?]
        at com.dev7ex.common.io.file.configuration.JsonConfiguration.load(JsonConfiguration.java:83) ~[?:?]
        at com.dev7ex.common.io.file.configuration.JsonConfiguration.load(JsonConfiguration.java:52) ~[?:?]
        at com.dev7ex.common.io.file.configuration.JsonConfiguration.load(JsonConfiguration.java:44) ~[?:?]
        at com.dev7ex.common.io.file.configuration.Configuration.loadFile(Configuration.java:51) ~[?:?]
        at com.dev7ex.multiworld.MultiWorldPlugin.onLoad(MultiWorldPlugin.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.io.EOFException: End of input at line 1 column 2 path $.
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[patched_1.16.5.jar:git-Paper-794]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.5.jar:git-Paper-794]
        ... 12 more
[12:23:31 INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:23:31 INFO]: Preparing level "world"
[12:23:32 INFO]: Preparing start region for dimension minecraft:overworld
[12:23:33 INFO]: Preparing spawn area: 0%
[12:23:33 INFO]: Preparing spawn area: 0%
[12:23:33 INFO]: Preparing spawn area: 0%
[12:23:33 INFO]: Preparing spawn area: 0%
[12:23:34 INFO]: Preparing spawn area: 0%
[12:23:34 INFO]: Preparing spawn area: 2%
[12:23:35 INFO]: Preparing spawn area: 7%
[12:23:35 INFO]: Preparing spawn area: 16%
[12:23:36 INFO]: Preparing spawn area: 18%
[12:23:36 INFO]: Preparing spawn area: 18%
[12:23:37 INFO]: Preparing spawn area: 19%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:43 INFO]: Preparing spawn area: 100%
[12:23:44 INFO]: Preparing spawn area: 100%
[12:23:44 INFO]: Preparing spawn area: 100%
[12:23:45 INFO]: Preparing spawn area: 100%
[12:23:45 INFO]: Preparing spawn area: 100%
[12:23:46 INFO]: Preparing spawn area: 100%
[12:23:46 INFO]: Preparing spawn area: 100%
[12:23:47 INFO]: Preparing spawn area: 100%
[12:23:47 INFO]: Preparing spawn area: 100%
[12:23:48 INFO]: Preparing spawn area: 100%
[12:23:48 INFO]: Preparing spawn area: 100%
[12:23:49 INFO]: Preparing spawn area: 100%
[12:23:49 INFO]: Time elapsed: 17695 ms
[12:23:49 INFO]: Preparing start region for dimension minecraft:the_nether
[12:23:50 INFO]: Preparing spawn area: 0%
[12:23:50 INFO]: Preparing spawn area: 0%
[12:23:50 INFO]: Preparing spawn area: 17%
[12:23:51 INFO]: Preparing spawn area: 40%
[12:23:51 INFO]: Preparing spawn area: 50%
[12:23:52 INFO]: Preparing spawn area: 69%
[12:23:53 INFO]: Preparing spawn area: 100%
[12:23:53 INFO]: Preparing spawn area: 100%
[12:23:53 INFO]: Preparing spawn area: 100%
[12:23:54 INFO]: Preparing spawn area: 100%
[12:23:54 INFO]: Preparing spawn area: 100%
[12:23:55 INFO]: Preparing spawn area: 100%
[12:23:55 INFO]: Preparing spawn area: 100%
[12:23:56 INFO]: Preparing spawn area: 100%
[12:23:56 INFO]: Preparing spawn area: 100%
[12:23:57 INFO]: Preparing spawn area: 100%
[12:23:57 INFO]: Preparing spawn area: 100%
[12:23:58 INFO]: Preparing spawn area: 100%
[12:23:58 INFO]: Preparing spawn area: 100%
[12:23:59 INFO]: Preparing spawn area: 100%
[12:23:59 INFO]: Time elapsed: 9718 ms
[12:23:59 INFO]: Preparing start region for dimension minecraft:the_end
[12:23:59 INFO]: Preparing spawn area: 0%
[12:23:59 INFO]: Preparing spawn area: 0%
[12:24:00 INFO]: Preparing spawn area: 31%
[12:24:00 INFO]: Preparing spawn area: 100%
[12:24:01 INFO]: Preparing spawn area: 100%
[12:24:01 INFO]: Preparing spawn area: 100%
[12:24:02 INFO]: Preparing spawn area: 100%
[12:24:02 INFO]: Time elapsed: 3273 ms
[12:24:02 INFO]: [FacilisCommon] Enabling FacilisCommon v1.0.5-SNAPSHOT
[12:24:02 INFO]: [FacilisCommon] Server Version: 1.16.5
[12:24:02 INFO]: [MultiWorld] Enabling MultiWorld v1.6.7-SNAPSHOT
[12:24:03 INFO]: [MultiWorld] Found: [5] Translations
[12:24:03 INFO]: [MultiWorld] Found: [0] World Generator
[12:24:03 WARN]: [FacilisCommon] This error was not triggered directly by FacilisCommon
[12:24:03 WARN]: [FacilisCommon] If you are sure that this error comes from FacilisCommon then write an issue on Github
[12:24:03 INFO]: [FacilisCommon] https://github.com/Dev7ex/FacilisCommon/issues
[12:24:03 WARN]: java.lang.NullPointerException: Cannot invoke "com.dev7ex.common.io.file.configuration.FileConfiguration.contains(String)" because the return value of "com.dev7ex.common.io.file.configuration.Configuration.getFileConfiguration()" is null
[12:24:03 WARN]:        at com.dev7ex.multiworld.world.DefaultWorldConfiguration.contains(DefaultWorldConfiguration.java:117)
[12:24:03 WARN]:        at com.dev7ex.multiworld.world.DefaultWorldProvider.onEnable(DefaultWorldProvider.java:59)
[12:24:03 WARN]:        at com.dev7ex.common.bukkit.plugin.module.PluginModuleManager.enableAllModules(PluginModuleManager.java:49)
[12:24:03 WARN]:        at com.dev7ex.common.bukkit.BukkitCommonPlugin.handlePluginEnable(BukkitCommonPlugin.java:73)
[12:24:03 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source)
[12:24:03 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:24:03 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:24:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:24:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[12:24:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:381)
[12:24:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:24:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[12:24:03 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[12:24:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599)
[12:24:03 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[12:24:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[12:24:03 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[12:24:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:24:03 INFO]: Running delayed init tasks
[12:24:03 INFO]: Done (35.827s)! For help, type "help"
Skynode: Server marked as running...
[12:24:03 INFO]: Timings Reset
[12:24:05 INFO]: [FacilisCommon] There is a new update available.
[12:24:05 INFO]: [FacilisCommon] Current Version: 1.0.5-SNAPSHOT
[12:24:05 INFO]: [FacilisCommon] New Version: 1.0.7-SNAPSHOT

**Comment by Dev7ex** [comment]
Yes, but what should I do now? The error occurs with an old MultiWorld version. This error will most likely no longer be present in the latest version. So what should I do in your opinion?

**Comment by aleksplay11** [comment]
ok, sorry to bother you, ill try to find the way to use new version.
